/**
 * The names of the tokens returned by the Argdown lexer.
 * These can be used to register [[IArgdownPlugin.tokenListeners]].
 */
export enum TokenNames {
  INCOMING_SUPPORT = "IncomingSupport",
  INCOMING_ATTACK = "IncomingAttack",
  INCOMING_UNDERCUT = "IncomingUndercut",
  CONTRADICTION = "Contradiction",
  OUTGOING_SUPPORT = "OutgoingSupport",
  OUTGOING_ATTACK = "OutgoingAttack",
  OUTGOING_UNDERCUT = "OutgoingUndercut",
  FREESTYLE = "Freestyle",
  UNUSED_CONTROL_CHAR = "UnusedControlChar",
  EMPTYLINE = "Emptyline",
  NEWLINE = "Newline",
  INFERENCE_START = "InferenceStart",
  INFERENCE_END = "InferenceEnd",
  STATEMENT_DEFINITION = "StatementDefinition",
  STATEMENT_REFERENCE = "StatementReference",
  STATEMENT_MENTION = "StatementMention",
  ARGUMENT_DEFINITION = "ArgumentDefinition",
  ARGUMENT_REFERENCE = "ArgumentReference",
  ARGUMENT_MENTION = "ArgumentMention",
  INDENT = "Indent",
  DEDENT = "Dedent",
  FRONT_MATTER = "FrontMatter",
  META_DATA = "MetaData",
  ORDERED_LIST_ITEM = "OrderedListItem",
  UNORDERED_LIST_ITEM = "UnorderedListItem",
  HEADING_START = "HeadingStart",
  LIST_DELIMITER = "ListDelimiter",
  STATEMENT_NUMBER = "StatementNumber",
  ASTERISK_BOLD_START = "AsteriskBoldStart",
  ASTERISK_BOLD_END = "AsteriskBoldEnd",
  ASTERISK_ITALIC_START = "AsteriskItalicStart",
  ASTERISK_ITALIC_END = "AsteriskItalicEnd",
  UNDERSCORE_BOLD_START = "UnderscoreBoldStart",
  UNDERSCORE_BOLD_END = "UnderscoreBoldEnd",
  UNDERSCORE_ITALIC_START = "UnderscoreItalicStart",
  UNDERSCORE_ITALIC_END = "UnderscoreItalicEnd",
  COMMENT = "Comment",
  TAG = "Tag",
  LINK = "Link",
  ESCAPED_CHAR = "EscapedChar",
  SPACES = "Spaces"
}
